name: CuyScout CI

on:
  push:
    paths:
      - "Sources/**"
      - "Tests/**"
      - "Package.swift"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "Sources/**"
      - "Tests/**"
      - "Package.swift"
      - ".github/workflows/ci.yml"

jobs:
  test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Verify Swift package
        run: swift test --parallel
      - name: Build executables
        run: swift build -c release

